### ISSUE TITLE
🛑 Kathy Wright & Company [kathywrightandco.com] is down

### ISSUE THREAD

**Issue by mrbrant89** [mrbrant89/mrb-monitoring#37]
In [`5cd6f32`](https://github.com/mrbrant89/mrb-monitoring/commit/5cd6f32c52e635313bada9a210f27e5c11bf23de
), Kathy Wright & Company [kathywrightandco.com] (https://kathywrightandco.com) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by nagamrb** [comment]
ssl issue will check

**Comment by mrbrant89** [comment]
She cancelled. We need to remove her from the monitoring. I will take care of that.

‬
 <https://mikessoaps.com/>
Michael R. Brant, PCM®, CDMP | Entrepreneur
T: ‭+1 (415) 763-5881 <tel:+14157635881>
E: ***@***.*** ***@***.***>
W: mrbrant.com <https://mrbrant.com/>
 
Schedule A Consultation <https://schedule.mrbmedia.org/michael_brant>	
 <https://www.facebook.com/mrbrant>	 <https://www.twitter.com/wthismichael>	 <https://linkedin.com/in/mrbrant>	 <https://www.instagram.com/wherethehellismichael>	 <https://www.youtube.com/channel/UCfhxZBObc68NSzKou6sfe-w>
 
 <https://mrbrant.com/>
The company accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.
